export const DMXMockData = {
  SystemDetails: {
    Id: '2156645d-2bb8-42cc-93f9-4cc32ec909f6',
    SystemName: 'DMX report',
    ProcessorId: 'b5252c04-9f52-4776-bf2d-91987c0db214',
    ProcessorName: 'CP4-R',
    CustomerName: '',
    Address1: '',
    Address2: '',
    City: '',
    State: '',
    Zip: '',
    Country: '',
    Notes: null,
    DealerId: '06d46190-8955-4a42-9e50-c164caa8b23a',
    DealerName: null,
    EmployeeName: 'Arun Palanichamy',
    PLUID: null,
    Address: '',
    AddressSingleLine: '',
    CustomerNumber: null
  },
  ReportDataUI: [
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 2,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      HeaderModuleName: 'DIN-GWDL',
      ModuleOutputNo: '1',
      IsSplitterOutput: false,
      LastDeviceIsSplitter: true,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '1-6',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL',
      UsedOutputs: 2,
      TotalOutputs: 2,
      ChannelUsed: 156,
      ChannelsRemaining: 356,
      TotalFixtures: 39,
      TotalWattages: 741,
      Cols: 18,
      Rows: 3,
      SlotNo: 1,
      SlotRange: '6',
      ParentModuleName: null,
      ParentOutputNumber: null,
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2, 3],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL',
              ModuleOutputNumber: '1',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: null,
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: true,
              OutputNo: null
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      HeaderModuleName: 'DIN-GWDL',
      ModuleOutputNo: '2',
      IsSplitterOutput: false,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '1-6',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL',
      UsedOutputs: 2,
      TotalOutputs: 2,
      ChannelUsed: 156,
      ChannelsRemaining: 356,
      TotalFixtures: 39,
      TotalWattages: 741,
      Cols: 18,
      Rows: 3,
      SlotNo: 1,
      SlotRange: '6',
      ParentModuleName: null,
      ParentOutputNumber: null,
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL',
              ModuleOutputNumber: '2',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: '',
              LoadGroupName: 'load26',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load26-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: '',
              LoadGroupName: 'load5',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load5-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '1',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '1',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 1
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load2',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load2-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 1
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load4',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load4-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 1
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '2',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '2',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 2
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load27',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load27-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 2
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load28',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load28-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 2
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 2,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '3',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2, 3],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '3',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 3
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load3',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load3-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 3
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 7,
      NoOfBox: [1, 2, 3, 4, 5, 6],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: false,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '4',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '4',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-2',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-3',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-4',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-9',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-8',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-7',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-6',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-5',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-10',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-11',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-12',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-13',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-14',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-19',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-18',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-17',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-16',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-15',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-20',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-21',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-22',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-23',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-24',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-29',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-28',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-27',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-26',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-25',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-30',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-31',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-32',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        }
      ]
    }
  ],
  ReportDataPDF: [
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 2,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      HeaderModuleName: 'DIN-GWDL',
      ModuleOutputNo: '1',
      IsSplitterOutput: false,
      LastDeviceIsSplitter: true,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '1-6',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL',
      UsedOutputs: 2,
      TotalOutputs: 2,
      ChannelUsed: 156,
      ChannelsRemaining: 356,
      TotalFixtures: 39,
      TotalWattages: 741,
      Cols: 18,
      Rows: 3,
      SlotNo: 1,
      SlotRange: '6',
      ParentModuleName: null,
      ParentOutputNumber: null,
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2, 3],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL',
              ModuleOutputNumber: '1',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: null,
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: true,
              OutputNo: null
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      HeaderModuleName: 'DIN-GWDL',
      ModuleOutputNo: '2',
      IsSplitterOutput: false,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '1-6',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL',
      UsedOutputs: 2,
      TotalOutputs: 2,
      ChannelUsed: 156,
      ChannelsRemaining: 356,
      TotalFixtures: 39,
      TotalWattages: 741,
      Cols: 18,
      Rows: 3,
      SlotNo: 1,
      SlotRange: '6',
      ParentModuleName: null,
      ParentOutputNumber: null,
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL',
              ModuleOutputNumber: '2',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: '',
              LoadGroupName: 'load26',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load26-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: '',
              LoadGroupName: 'load5',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load5-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: null
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '1',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '1',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 1
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load2',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load2-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 1
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load4',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load4-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 1
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 3,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '2',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '2',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 2
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load27',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load27-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 2
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load28',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load28-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 2
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 1,
      NoOfBox: [],
      NoOfLastRowDevices: 2,
      ContinueNextPage: false,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '3',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [1, 2, 3],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '3',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 3
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: 'load3',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: 'load3-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 3
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 5,
      NoOfBox: [1, 2, 3, 4],
      NoOfLastRowDevices: 5,
      ContinueNextPage: true,
      PreviousPageContinuation: false,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '4',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '4',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-1',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-2',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-3',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-4',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-9',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-8',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-7',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-6',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-5',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-10',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-11',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-12',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-13',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-14',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-19',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-18',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-17',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-16',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-15',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-20',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-21',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-22',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-23',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-24',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        }
      ]
    },
    {
      NoOfRow: 2,
      NoOfBox: [1],
      NoOfLastRowDevices: 4,
      ContinueNextPage: false,
      PreviousPageContinuation: true,
      PageBreak: true,
      ModuleName: 'Enclosure (R1,S7-12) : DIN-GWDL-SPLTR',
      HeaderModuleName: 'DIN-GWDL-SPLTR',
      ModuleOutputNo: '4',
      IsSplitterOutput: true,
      LastDeviceIsSplitter: false,
      RoomName: 'Equipment Room',
      RoomGroupName: '',
      EnclosureName: 'Enclosure',
      EnclosureModel: 'DIN-EN-3X18',
      RailNumber: 1,
      DinSlot: '7-12',
      SerialNumber: null,
      ModuleTypeName: 'DIN-GWDL-SPLTR',
      UsedOutputs: 4,
      TotalOutputs: 4,
      ChannelUsed: 148,
      ChannelsRemaining: 364,
      TotalFixtures: 37,
      TotalWattages: 703,
      Cols: 18,
      Rows: 3,
      SlotNo: 7,
      SlotRange: '6',
      ParentModuleName: 'Enclosure (R1,S1-6) : DIN-GWDL',
      ParentOutputNumber: '1',
      ParentIsSplitter: false,
      DmxReportRowDataList: [
        {
          NoOfDevicesLeft: [],
          DmxReportDataList: [
            {
              ModuleName: 'DIN-GWDL-SPLTR',
              ModuleOutputNumber: '4',
              RoomName: null,
              RoomGroupName: null,
              LoadGroupName: null,
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: null,
              IsDMXSplitterOutput: true,
              IsSplitterOutput: true,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-25',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-26',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-27',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-28',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        },
        {
          NoOfDevicesLeft: [1],
          DmxReportDataList: [
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-32',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-31',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-30',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            },
            {
              ModuleName: null,
              ModuleOutputNumber: null,
              RoomName: 'Equipment Room',
              RoomGroupName: null,
              LoadGroupName: '1',
              SerialNumber: null,
              FixtureTypeName: null,
              FixtureName: '1-29',
              IsDMXSplitterOutput: false,
              IsSplitterOutput: false,
              IsSplitter: false,
              OutputNo: 4
            }
          ]
        }
      ]
    }
  ]
};
